domain: dailybible.biz
onboarding:
  completed_at: '2026-04-24T23:08:04.570594+00:00'
  gsc_property_added: true
  gsc_verified: true
  vercel_configured: true
  verification_token: google-site-verification=Sp1VTNWGWV-a9veQftt89REven2Gs_wT1jqkKYj6luE
site_id: dailybible-biz
site_name: Dailybible
