domain: gutprotocol.org
onboarding:
  completed_at: '2026-04-25T02:31:08.413919+00:00'
  gsc_property_added: true
  gsc_verified: true
  vercel_configured: true
  verification_token: google-site-verification=uy45AU44FxN3DNR9EL5cZGL6fW2Cv1ooxhPf8PocHN8
site_id: gutprotocol-org
site_name: Gutprotocol
