domain: helloyou.site
onboarding:
  completed_at: '2026-04-25T02:31:12.546818+00:00'
  gsc_property_added: true
  gsc_verified: true
  vercel_configured: true
  verification_token: google-site-verification=U4w3jRCAUjNoEt1iy9Vkft0UHyWzVnZQxixVyFR6BaY
site_id: helloyou-site
site_name: Helloyou
