domain: lamphill.org
onboarding:
  completed_at: '2026-04-25T02:30:12.836339+00:00'
  gsc_property_added: true
  gsc_verified: true
  vercel_configured: true
  verification_token: ''
site_id: lamphill-org
site_name: Lamphill
